version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-metastore
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:standalone-metastore-nightly
    container_name: hive-metastore
    depends_on:
      - postgres
    environment:
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hive
      - HIVE_METASTORE_DB=metastore
      - HIVE_METASTORE_URI=thrift://0.0.0.0:9083
      - HIVE_METASTORE_JDBC_URL=jdbc:postgresql://postgres:5432/metastore
      - HIVE_METASTORE_JDBC_USERNAME=hive
      - HIVE_METASTORE_JDBC_PASSWORD=hive
      - HIVE_CONF_hive_metastore_warehouse_dir=/user/hive/warehouse
    ports:
      - "9083:9083"
    volumes:
      - hive-metastore-data:/opt/hive-metastore/metastore_db

  spark-master:
    image: spark:3.4.1
    pull_policy: never
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: spark:3.4.1
    pull_policy: never
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
    ports:
      - "8081:8081"

  trino:
    image: trinodb/trino:478
    pull_policy: never
    container_name: trino
    depends_on:
      - hive-metastore
    ports:
      - "8082:8080"
    volumes:
      - ./trino-config:/etc/trino
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx1g

volumes:
  postgres-data:
  hive-metastore-data:
